In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
df = pd.read_csv('/content/data.csv')

In [ ]:
df

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated,street,city,statezip,country
0,2014-05-02 00:00:00,3.130000e+05,3.0,1.50,1340,7912,1.5,0,0,3,1340,0,1955,2005,18810 Densmore Ave N,Shoreline,WA 98133,USA
1,2014-05-02 00:00:00,2.384000e+06,5.0,2.50,3650,9050,2.0,0,4,5,3370,280,1921,0,709 W Blaine St,Seattle,WA 98119,USA
2,2014-05-02 00:00:00,3.420000e+05,3.0,2.00,1930,11947,1.0,0,0,4,1930,0,1966,0,26206-26214 143rd Ave SE,Kent,WA 98042,USA
3,2014-05-02 00:00:00,4.200000e+05,3.0,2.25,2000,8030,1.0,0,0,4,1000,1000,1963,0,857 170th Pl NE,Bellevue,WA 98008,USA
4,2014-05-02 00:00:00,5.500000e+05,4.0,2.50,1940,10500,1.0,0,0,4,1140,800,1976,1992,9105 170th Ave NE,Redmond,WA 98052,USA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4595,2014-07-09 00:00:00,3.081667e+05,3.0,1.75,1510,6360,1.0,0,0,4,1510,0,1954,1979,501 N 143rd St,Seattle,WA 98133,USA
4596,2014-07-09 00:00:00,5.343333e+05,3.0,2.50,1460,7573,2.0,0,0,3,1460,0,1983,2009,14855 SE 10th Pl,Bellevue,WA 98007,USA
4597,2014-07-09 00:00:00,4.169042e+05,3.0,2.50,3010,7014,2.0,0,0,3,3010,0,2009,0,759 Ilwaco Pl NE,Renton,WA 98059,USA
4598,2014-07-10 00:00:00,2.034000e+05,4.0,2.00,2090,6630,1.0,0,0,3,1070,1020,1974,0,5148 S Creston St,Seattle,WA 98178,USA
4599,2014-07-10 00:00:00,2.206000e+05,3.0,2.50,1490,8102,2.0,0,0,4,1490,0,1990,0,18717 SE 258th St,Covington,WA 98042,USA

In [ ]:
df = df.drop(columns=['date','street','statezip'])

In [ ]:
df

,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated,city,country
0,3.130000e+05,3.0,1.50,1340,7912,1.5,0,0,3,1340,0,1955,2005,Shoreline,USA
1,2.384000e+06,5.0,2.50,3650,9050,2.0,0,4,5,3370,280,1921,0,Seattle,USA
2,3.420000e+05,3.0,2.00,1930,11947,1.0,0,0,4,1930,0,1966,0,Kent,USA
3,4.200000e+05,3.0,2.25,2000,8030,1.0,0,0,4,1000,1000,1963,0,Bellevue,USA
4,5.500000e+05,4.0,2.50,1940,10500,1.0,0,0,4,1140,800,1976,1992,Redmond,USA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4595,3.081667e+05,3.0,1.75,1510,6360,1.0,0,0,4,1510,0,1954,1979,Seattle,USA
4596,5.343333e+05,3.0,2.50,1460,7573,2.0,0,0,3,1460,0,1983,2009,Bellevue,USA
4597,4.169042e+05,3.0,2.50,3010,7014,2.0,0,0,3,3010,0,2009,0,Renton,USA
4598,2.034000e+05,4.0,2.00,2090,6630,1.0,0,0,3,1070,1020,1974,0,Seattle,USA
4599,2.206000e+05,3.0,2.50,1490,8102,2.0,0,0,4,1490,0,1990,0,Covington,USA

In [ ]:
df.shape

(4600, 15)

In [ ]:
df['city'].value_counts()

city
Seattle                1573
Renton                  293
Bellevue                286
Redmond                 235
Kirkland                187
Issaquah                187
Kent                    185
Auburn                  176
Sammamish               175
Federal Way             148
Shoreline               123
Woodinville             115
Maple Valley             96
Mercer Island            86
Burien                   74
Snoqualmie               71
Kenmore                  66
Des Moines               58
North Bend               50
Covington                43
Duvall                   42
Lake Forest Park         36
Bothell                  33
Newcastle                33
Tukwila                  29
SeaTac                   29
Vashon                   29
Enumclaw                 28
Carnation                22
Normandy Park            18
Clyde Hill               11
Fall City                11
Medina                   11
Black Diamond             9
Ravensdale                7
Pacific                   6
Algona                    5
Yarrow Point              4
Skykomish                 3
Milton                    2
Preston                   2
Inglewood-Finn Hill       1
Snoqualmie Pass           1
Beaux Arts Village        1
Name: count, dtype: int64

In [ ]:
a = {}
s = 0

for i in df['city']:
  if i not in a:
    a[i] = s
    s = s+1
  else:
    pass
df['city'] = df['city'].map(a).astype(int)

In [ ]:
df['city'].unique()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43])

In [ ]:
df['country'].value_counts()

country
USA    4600
Name: count, dtype: int64

In [ ]:
df['country']=df['country'].map({'USA':0}).astype(int)

In [ ]:
df['country']

0       0
1       0
2       0
3       0
4       0
       ..
4595    0
4596    0
4597    0
4598    0
4599    0
Name: country, Length: 4600, dtype: int64

In [ ]:
x = df.iloc[:,1: ]
y = df.iloc[:,0]

In [ ]:
x

,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated,city,country
0,3.0,1.50,1340,7912,1.5,0,0,3,1340,0,1955,2005,0,0
1,5.0,2.50,3650,9050,2.0,0,4,5,3370,280,1921,0,1,0
2,3.0,2.00,1930,11947,1.0,0,0,4,1930,0,1966,0,2,0
3,3.0,2.25,2000,8030,1.0,0,0,4,1000,1000,1963,0,3,0
4,4.0,2.50,1940,10500,1.0,0,0,4,1140,800,1976,1992,4,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4595,3.0,1.75,1510,6360,1.0,0,0,4,1510,0,1954,1979,1,0
4596,3.0,2.50,1460,7573,2.0,0,0,3,1460,0,1983,2009,3,0
4597,3.0,2.50,3010,7014,2.0,0,0,3,3010,0,2009,0,18,0
4598,4.0,2.00,2090,6630,1.0,0,0,3,1070,1020,1974,0,1,0
4599,3.0,2.50,1490,8102,2.0,0,0,4,1490,0,1990,0,23,0

In [ ]:
y

0       3.130000e+05
1       2.384000e+06
2       3.420000e+05
3       4.200000e+05
4       5.500000e+05
            ...
4595    3.081667e+05
4596    5.343333e+05
4597    4.169042e+05
4598    2.034000e+05
4599    2.206000e+05
Name: price, Length: 4600, dtype: float64

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(x,y,test_size = 0.2,random_state=15)

In [ ]:
len(X_train),len(y_train)

(3680, 3680)

In [ ]:
len(X_test),len(y_test)

(920, 920)

In [ ]:
from sklearn.linear_model import LinearRegression
reg = LinearRegression()
reg.fit(X_train,y_train)

LinearRegression()

In [ ]:
reg.coef_

array([-5.46559918e+04,  6.26306415e+04,  1.57183615e+02, -5.52988632e-01,
        1.69173293e+04,  2.33990729e+05,  5.75377020e+04,  3.72674955e+04,
        1.01455996e+02,  5.57276191e+01, -1.93974751e+03,  3.62534295e+00,
       -3.96186763e+03,  0.00000000e+00])

In [ ]:
reg.intercept_

np.float64(3758621.60806642)

In [ ]:
#train

In [ ]:
y_train_predictions = reg.predict(X_train)

In [ ]:
from sklearn.metrics import root_mean_squared_error,r2_score
print(f'loss:{root_mean_squared_error(y_train,y_train_predictions)}')
print(f'accuracy:{r2_score(y_train,y_train_predictions)}')

loss:538922.8048083489
accuracy:0.18599967898923087

In [ ]:
#test

In [ ]:
y_test_predictions = reg.predict(X_test)

In [ ]:
print(f'loss:{root_mean_squared_error(y_test,y_test_predictions)}')
print(f'accuracy:{r2_score(y_test,y_test_predictions)}')

loss:276087.61403448205
accuracy:0.5293181046151961

In [ ]:
import pickle

In [ ]:
with open('MLR_model.pkl','wb')as f:
  pickle.dump(reg,f)

In [ ]:
with open('/content/MLR_model.pkl','rb')as f:
  m= pickle.load(f)